services:
  sitegen27:
    image: 'vlad1kudelko/sitegen27:1.1'
    volumes:
      - '.:/app/www'
    environment:
      - 'DOMAIN=vlad1kudelko.github.io'
    entrypoint: [ 'bash', '-c', 'node /app/build.js && cd tailwind && bash build.sh && tail -f /dev/null']
    healthcheck:
      test: ["CMD", "test", "-f", "/app/www/public/index.html"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  server:
    image: 'nginx:alpine'
    ports:
      - '8000:80'
    volumes:
      - './public:/usr/share/nginx/html'
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      sitegen27:
        condition: service_healthy
    restart: unless-stopped
