name: CI
on:
  push:
    branches:
      - "main"
env:
    DOMAIN: 'vlad1kudelko.gitlab.io'
jobs:
  build:
    runs-on: vlad1kudelko/sitegen27
    steps:
      - run: node /app/build.js && cd tailwind && bash build.sh
