name: ci
on:
  push:
    branches:
      - "main"
jobs:
  container-test-job:
  build:
    runs-on: ubuntu-latest
    container:
      image: vlad1kudelko/sitegen27
      env:
        DOMAIN: 'vlad1kudelko.gitlab.io'
    steps:
      - run: node /app/build.js && cd tailwind && bash build.sh
