name: ci
on:
  push:
    branches:
      - "main"
env:
  DOMAIN: 'vlad1kudelko.gitlab.io'
jobs:
  build:
    runs-on: ubuntu-latest
    container: vlad1kudelko/sitegen27
    steps:
      - run: >
        cd /app/www && node /app/build.js ;
        cd /app/www/tailwind && bash build.sh ;
