name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vlad1kudelko/sitegen27:latest
      options: --user root
      env:
        DOMAIN: vlad1kudelko.gitlab.io
    steps:
      - uses: actions/checkout@v4
      - run: node /app/build.js && cd tailwind && bash build.sh
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - uses: actions/deploy-pages@v4
        id: deployment
