name: ci
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vlad1kudelko/sitegen27
      volumes:
        - '.:/app/www'
      env:
        DOMAIN: 'vlad1kudelko.gitlab.io'
    steps:
      - run: |
          cd /app/www && node /app/build.js
          cd /app/www/tailwind && bash build.sh
