name: ci
on:
  push:
    branches:
      - "main"
# env:
  # DOMAIN: vlad1kudelko.gitlab.io
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vlad1kudelko/sitegen27
      volumes:
        - .:/app/www
      env:
        DOMAIN: vlad1kudelko.gitlab.io
      entrypoint: [ 'bash', '-c', 'node /app/build.js && cd tailwind && bash build.sh']
    steps:
      - uses: actions/checkout@v4
      - run: |
          pwd ; ls -al ; ls -al /app ; ls -al /app/www
          # node /app/build.js && cd tailwind && bash build.sh
