name: ci
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t sitegen27 ./sitegen27
      - name: Run build
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/www:/app/www \
            -e DOMAIN=crafthomelab.ru \
            sitegen27 \
            bash start.sh
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: www/public
      - uses: actions/deploy-pages@v4
        id: deployment
