name: ci
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vlad1kudelko/sitegen27
      env:
        DOMAIN: 'vlad1kudelko.gitlab.io'
    steps:
      - uses: actions/checkout@v4
      - run: |
          pwd ; ls -al ; ls -al /app ; ls -al /app/www
          node /app/build.js && cd tailwind && bash build.sh
